### ISSUE TITLE
Login: Kleurtje forgot password op gele achtergrond is nogal intens qua contrast :-)

### ISSUE THREAD

**Issue by rikschennink** [ChanelZM/css_to_the_rescue#1]
Tip, haal voor en achtergrond kleuren even door http://contrastchecker.com/ om te kijken of ze contrasterend genoeg zijn voor bijvoorbeeld mensen met kleurenblindheid of slechtzienden.

**Comment by ChanelZM** [comment]
Goeie tip thanks!
